version: 2
updates:

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci(github-actions): "
    labels:
      - "ci"
    assignees:
      - "hakadoriya/owner"
    reviewers:
      - "hakadoriya/owner"
    groups:
      dependencies:
        patterns:
          - "*"
